pre-commit/pre-commit-hooks

README.md
hooks.yaml
pre_commit_hooks/check_docstring_first.py
setup.py
tests/check_docstring_first_test.py

Resolves https://github.com/pre-commit/pre-commit/issues/182

Add check-docstring-first hook.

---

pre_commit_hooks/requirements_txt_fixer.py

Fixes https://github.com/pre-commit/pre-commit-hooks/issues/20

Print on requirements.txt failure

---

README.md
hooks.yaml

I got tripped up because this is the only hook that requires arguments.

change wording so that people know this hook needs arguments.

---

.travis.yml
hooks.yaml
pre_commit_hooks/check_added_large_files.py
pre_commit_hooks/check_case_conflict.py
pre_commit_hooks/util.py
pylintrc
setup.py
testing/util.py
tests/check_added_large_files_test.py
tests/check_case_conflict_test.py
tests/conftest.py

This is for #21. I'm not 100% sure about the validity of my approach or of my test cases, so comments/criticism are welcome.

Add check_case_conflict hook

---

.travis.yml
pre_commit_hooks/check_yaml.py
tox.ini

Use the CLoader when present to validate yaml

---

pre_commit_hooks/end_of_file_fixer.py

I'll hook this up to appveyor after

Fix end-of-file-fixer on windows

---

pre_commit_hooks/tests_should_end_in_test.py
tests/tests_should_end_in_test_test.py

Add --django flag to test name checker

---

README.md
hooks.yaml
pre_commit_hooks/check_merge_conflict.py
setup.py
tests/check_merge_conflict_test.py

Add check-merge-conflict hook

---

pre_commit_hooks/check_merge_conflict.py
pylintrc
tests/check_merge_conflict_test.py

Only check merge conflicts on conflict commits

---

pre_commit_hooks/debug_statement_hook.py

q is a debugging tool: https://pypi.python.org/pypi/q

Add q as a debug statement

---

pre_commit_hooks/detect_aws_credentials.py

This change causes the name of the files containing the aws credentials to be printed when the pre-commit hooks are run. It's heavily based on the Detect Private Key code.

Show names of files containing aws credentials

---

pre_commit_hooks/util.py

This makes the command compatible with older versions of git.

Reformatted --diff-filter git argument

---

.coveragerc
.travis.yml
get-git-lfs.py
pre_commit_hooks/check_added_large_files.py
pre_commit_hooks/util.py
tests/check_added_large_files_test.py

Works pretty well I think.
I ran into https://github.com/github/git-lfs/issues/913 and https://github.com/github/git-lfs/issues/914 while implementing, but it should mostly work.
@JannKleen it took me a while but I finally got around to this :)

Teach check-large-files-added about git-lfs.  Reslves #82.

---

pre_commit_hooks/check_symlinks.py
testing/resources/broken_symlink
testing/resources/working_symlink
tests/check_symlinks_test.py

New hook tests for broken symlinks

---

pre_commit_hooks/detect_aws_credentials.py
tests/detect_aws_credentials_test.py

Improve error message when credentials file is not provided

---

README.md
pre_commit_hooks/fix_encoding_pragma.py
tests/fix_encoding_pragma_test.py

Add a --remove option to fix-encoding-pragma

---

tests/check_merge_conflict_test.py

@asottile 
Adds support for [diff3 style merge conflicts](http://psung.blogspot.com/2011/02/reducing-merge-headaches-git-meets.html).

Add diff3 conflictstyle support for git merge conflicts.

---

pre_commit_hooks/pretty_format_json.py

Fix exception raising logic to match validation issues

---

pre_commit_hooks/fix_encoding_pragma.py
tests/fix_encoding_pragma_test.py

Allow encoding pragma to be customizable

---

pre_commit_hooks/check_yaml.py

Use safe_load as per PyYAML documentation

---

pre_commit_hooks/pretty_format_json.py
testing/resources/top_sorted_json.json
tests/pretty_format_json_test.py

This adds custom sorting to preferentially add a list of top keys
at the start of any json hash in the json document

adds top keys list of keys in hashes to put at the top of a hash

---

.pre-commit-hooks.yaml
tests/meta_test.py

Add .pre-commit-hooks.yaml for forward compatibility

---

.pre-commit-config.yaml
pre_commit_hooks/autopep8_wrapper.py
pre_commit_hooks/check_added_large_files.py
pre_commit_hooks/check_ast.py
pre_commit_hooks/check_byte_order_marker.py
pre_commit_hooks/check_case_conflict.py
pre_commit_hooks/check_docstring_first.py
pre_commit_hooks/check_json.py
pre_commit_hooks/check_symlinks.py
pre_commit_hooks/check_xml.py
pre_commit_hooks/debug_statement_hook.py
pre_commit_hooks/detect_private_key.py
pre_commit_hooks/end_of_file_fixer.py
pre_commit_hooks/pretty_format_json.py
pre_commit_hooks/requirements_txt_fixer.py
pre_commit_hooks/string_fixer.py
pre_commit_hooks/tests_should_end_in_test.py
pre_commit_hooks/trailing_whitespace_fixer.py
tests/readme_test.py

- See https://github.com/asottile/pyupgrade
- This also puts the nail in the coffin for py26 support (which was dropped long ago)

Add pyupgrade

---

pre_commit_hooks/check_merge_conflict.py
tests/check_merge_conflict_test.py

Support rebase conflicts in check-merge-conflicts

---

.pre-commit-config.yaml
.pre-commit-hooks.yaml
hooks.yaml
tests/meta_test.py

Use 0.15.0 types

---

.pre-commit-hooks.yaml
README.md
hooks.yaml
pre_commit_hooks/check_executables_have_shebangs.py
setup.py
tests/check_executables_have_shebangs_test.py

Add a checker for executables without shebangs

---

tests/check_added_large_files_test.py
tests/forbid_new_submodules_test.py

Don't gpg sign during test

---

.coveragerc
pre_commit_hooks/check_ast.py
tox.ini

Report full version in check-ast

---

.pre-commit-hooks.yaml

Partially reverses #221 -- I realized while falling asleep the other night why this was the way it was :)

Use a better regex for name-tests-test

---

setup.py

Fix mixed-line-endings entrypoint

---

pre_commit_hooks/mixed_line_ending.py
tests/mixed_line_ending_test.py

Fix mixed-line-endings --fix=... when whole file is a different ending

---

README.md
pre_commit_hooks/check_yaml.py
tests/check_yaml_test.py

CC @geekobi from https://github.com/pre-commit/pre-commit/issues/635

Add an --allow-multiple-documents option to check-yaml

---

pre_commit_hooks/check_vcs_permalinks.py

This has a weird failure mode otherwise in python 3

Add a flush

---

tests/check_merge_conflict_test.py
tests/conftest.py
tests/forbid_new_submodules_test.py

Committed via https://github.com/asottile/all-repos

Replace deprecated yield_fixture with fixture

---

pre_commit_hooks/no_commit_to_branch.py
tests/check_no_commit_to_branch_test.py

Fix no-commit-to-branch when not on a branch

---

README.md
pre_commit_hooks/check_yaml.py
tests/check_yaml_test.py

Add an `--unsafe` option to `check-yaml`

---

tests/check_merge_conflict_test.py

pull with --no-rebase

---

README.md

Committed via https://github.com/asottile/all-repos

Suggest https:// git urls

---

.pre-commit-hooks.yaml

Don't run end-of-file-fixer hook for the commit-msg stage

---

pre_commit_hooks/check_yaml.py
setup.py

switch from pyyaml to ruamel.yaml

---

pre_commit_hooks/string_fixer.py
tests/string_fixer_test.py

Fix crlf line endings for double-quote-string-fixer

---

tests/check_added_large_files_test.py

Fixed broken CI caused by missing HOME.
Fixes: #402

Assure we have HOME defined during testing

---

pre_commit_hooks/requirements_txt_fixer.py
tests/requirements_txt_fixer_test.py

Resolves #414 
- add new line post reading requirements file.
- change `before` variable from tuple .
- to list, add test cases.
This maintains all previous behaviour(s) as given by the test cases.
(my first ever OS contribution, any and **all**   feedback is welcome)

add new line after reading requirements file

---

README.md

Add note about sort-simple-yaml's opt-in behaviour

---

README.md

document --no-ensure-ascii

---

pre_commit_hooks/tests_should_end_in_test.py
tests/tests_should_end_in_test_test.py

Noticed this when reading the code -- the regular expression doesn't escape the . in the .py

fix regular expression for test files

---

.pre-commit-hooks.yaml
README.md

officially deprecate the flake8 hook

---

pre_commit_hooks/detect_aws_credentials.py
tests/detect_aws_credentials_test.py

This PR resolves the following - issue https://github.com/pre-commit/pre-commit-hooks/issues/449

Skip empty key variables in detect_aws_credentials

---

pre_commit_hooks/debug_statement_hook.py

I've added wdb to the DEBUG_STATEMENTS
Resolves #451

debug statements - add wdb

---

.pre-commit-hooks.yaml

This will make it show up on https://pre-commit.com/hooks.html
Relates to #344

Extend deprecation message to description

---

.pre-commit-config.yaml
setup.cfg
tests/sort_simple_yaml_test.py

[python 3 statement - 3.6.0](https://github.com/asottile/scratch/wiki/python-3-statement#360)
(due to broken `NamedTuple` in 3.6.0)

pre-commit-hooks: python3.6.1+

---

pre_commit_hooks/requirements_txt_fixer.py
tests/requirements_txt_fixer_test.py

[#465] Handled multiline dependencies

---

pre_commit_hooks/check_case_conflict.py
tests/check_case_conflict_test.py

check also directories in check_case_conflict

---

pre_commit_hooks/check_vcs_permalinks.py
tests/check_vcs_permalinks_test.py

Disallow any branch name in checks_vcs_permalinks

---

tests/detect_aws_credentials_test.py

Committed via https://github.com/asottile/all-repos

Use more inclusive language

---

pre_commit_hooks/debug_statement_hook.py

Can we include [pdbr](https://github.com/cansarigol/pdbr) package into the `DEBUG_STATEMENTS` ?

Added pdbr into debug statements

---

README.md

Re: https://github.com/pre-commit/pre-commit-hooks/blob/40cc31b02ceb72045509576e51d9c82503751422/pre_commit_hooks/file_contents_sorter.py#L54-L65

Document file-contents-sorter arguments

---

README.md

Document --assume-in-merge in doc of check-merge-conflict

Document check-merge-conflict argument

---

pre_commit_hooks/check_shebang_scripts_are_executable.py

Replacec PR #773 .
resolves #770

Add instruction to change executable mode on windows

---

.pre-commit-hooks.yaml
README.md

from the recipe in #707
```console
$ pre-commit  try-repo . forbid-submodules --all-files
[WARNING] Creating temporary repo with uncommitted changes...
===============================================================================
Using config:
===============================================================================
repos:
-   repo: /tmp/tmpsa1bou80/shadow-repo
rev: 56154e7b7ef456dd9f8878854319891c00717415
hooks:
-   id: forbid-submodules
===============================================================================
[INFO] Initializing environment for /tmp/tmpsa1bou80/shadow-repo.
forbid submodules........................................................Failed
- hook id: forbid-submodules
- exit code: 1
submodules are not allowed in this repository:
astpretty
```

add forbid-submodules hook

---

.pre-commit-hooks.yaml
tests/check_illegal_windows_names_test.py

support more illegal Windows filenames

---

tests/check_merge_conflict_test.py
tests/check_vcs_permalinks_test.py
tests/no_commit_to_branch_test.py

remove master references from tests
