hooks.yaml
In Puppet a common practice is to add eyaml files to hiera for security purposes.
=> Add eyaml support for check-yaml hook

pre_commit_hooks/check_merge_conflict.py, tests/check_merge_conflict_test.py
Several markup formats, such as Markdown or Re(Structured)Text can format titles as text with '=' characters as double underlining, like this:
```
My Page Title
=============
Lorem ipsum...
```
Rather that considering any line starting with seven '=' as a conflict marker, require a space (or line-ending newline) after the equals.
This could still create a false positive for a seven character title, like "Problem", but the markup formats generally allow extra '=' characters, so by formatting the text like this:
```
Problem
========
Not...
```
these pre-commit warnings can be avoided.
=> Don't report markup titles as merge conflicts

pre_commit_hooks/check_merge_conflict.py, tests/check_merge_conflict_test.py
Building on [PR#55](https://github.com/pre-commit/pre-commit-hooks/pull/55), this subsumes those changes and adds some refactoring of the tests to better reflect the fact that we want to run merge conflict detection any time we are in a merge, whether the particular file we're looking at is in a merge state or not.  We also want to use git to generate a real merge conflict and check that we detect it (in case formatting changes for some reason).
Also, rename the function that checks whether repository is pending merge to reflect that it is doing that, and not actually detecting merge conflict.
=> refactor detect_merge_conflict_test.py

README.md, pre_commit_hooks/detect_private_key.py, pre_commit_hooks/trailing_whitespace_fixer.py, pylintrc, tests/trailing_whitespace_fixer_test.py
Markdown uses two or more trailing spaces on a line to indicate a forced
line break `<br/>` - these will be preserved for files with a markdown
extension (default = `.md` or `.markdown`).
Add `--markdown-linebreak-ext=X,Y` to set extensions (`*` matches any),
and `--no-markdown-linebreak-ext` to disable this feature.
Update README.md to include information on these arguments as well as
arguments added to other hooks
=> Implement Markdown trailing space line break preservation

README.md, hooks.yaml, pre_commit_hooks/detect_aws_credentials.py, requirements-dev.txt, setup.py, testing/resources/nonsense.txt, testing/resources/sample_aws_credentials, testing/resources/with_no_secrets.txt, testing/resources/with_secrets.txt, tests/detect_aws_credentials_test.py
add aws credential checking ONLY FOR YOUR OWN **SECRET** credentials if they're set in a configurable credentials file (AWS CLI tools' format), access keys are ignored.
I haven't had time to figure out how to configure the arguments from a .pre-commit-config yaml file, some help would be nice so I can update the readme further.
Let me know if anything's missing in order for this to get accepted.
=> AWS credential checking

pre_commit_hooks/detect_private_key.py, tests/detect_private_key_test.py
Currently it prints *the entire content* of the problem file (which might be really long, e.g. a Python test file with embedded dummy key) but doesn't actually print the file name.
=> detect_private_key: print *filenames*, not the key

README.md, hooks.yaml, pre_commit_hooks/check_ast.py, setup.py, tests/check_ast_test.py
We want to use this as follows:
```yaml
-   id: check-ast
language_version: python3.4
```
to "encourage" people to write python3 compatible syntax in our currently-python2.7 codebase
=> Add a hook to verify python ast.

pre_commit_hooks/requirements_txt_fixer.py, tests/requirements_txt_fixer_test.py
Every time I `pip freeze` to update my requirements.txt and then run pre-commit, I get diffs like:
```diff
--- a/requirements.txt
+++ b/requirements.txt
@@ -1,6 +1,8 @@
+Django==1.8.3
+PyMySQL==0.6.6
+SQLAlchemy==1.0.8
colorama==0.3.3
cracklib==2.9.3
-Django==1.8.3
dnspython3==1.12.0
ecdsa==0.13
gunicorn==19.3.0
@@ -10,7 +12,5 @@ paramiko==1.15.2
pexpect==3.2
pyasn1==0.1.8
pycrypto==2.6.1
-PyMySQL==0.6.6
pysnmp==4.2.5
requests==2.7.0
-SQLAlchemy==1.0.8
```
IMO the pip behavior is more useful (putting capitalized deps at the top seems unhelpful, especially since they can appear lowercase or uppercase and still be correct). Plus this avoids unnecessary churn.
FWIW I think this is a behavior of newer versions of pip; old pip (1.5.6) seems to keep capitals at the top, while the latest …
=> Sort requirements.txt case-insensitively

pre_commit_hooks/tests_should_end_in_test.py, tests/tests_should_end_in_test_test.py
Addresses issue at https://github.com/pre-commit/pre-commit-hooks/issues/88, where the regex for django mistook the directory as part of the filename and, as a result failed to flag bad filenames.  
Implementation itself, strips off the directory path, leaving just the basename so that we don't have to run endswith. Also, re.match() wouldn't have worked with directories such as 'foo/tests/bar' anyways since it checks at the **beginning** of the string.
=> Fixed regex matching for django test file names

README.md
`*` is being interpreted as italic unless wrapped in code block.
=> Fix code syntax in README

README.md, pre_commit_hooks/pretty_format_json.py
This allows to disable the sort on the keys.
Still works the same as before if the new argument is not specified.
=> Addding no-sort-keys to pretty_format_json

tests/check_added_large_files_test.py, tests/check_case_conflict_test.py, tests/check_merge_conflict_test.py, tests/conftest.py
1. Disable automatic `git commit` GPG-signing, since that requires interaction. This issue was encountered in practice by me, causing spurious test failures.
2. In case path operands could turn out to start with dashes, escape the operand list with `--`.
=> Increase robustness of tests involving `git`

hooks.yaml
* Add extensions for AsciiDoctor, C, C++, OCaml, R, Rust.
* Reorder alphabetically.
See #125.
=> Add file patterns for trailing whitespace fixer

pre_commit_hooks/requirements_txt_fixer.py, tests/requirements_txt_fixer_test.py
Requirement fixer does not handles the requirements of the format `-e git+ssh://git_url@tag#egg=req` properly.
This results in these kind of requirements always ordered to the file top.
This is not in sync with the output given by `pip freeze`.
=> handle editable requirements properly

hooks.yaml
* Modifies the `end-of-file-fixer` and `trailing-whitespace` hooks to include .groovy and .tex (TeX/LaTeX) files.
We have some Groovy files as well as some LaTeX files that could benefit from whitespace fixing awesomeness!
@Lucas-C @asottile
=> Add .groovy and .tex files to whitespace hooks

hooks.yaml
Add `.j2` file extension (Jinja2 templates) to trailing-whitespace and end-of-file-fixer
=> add j2 extension to trailing-whitespace and end-of-file-fixer

README.md, hooks.yaml, pre_commit_hooks/forbid_new_submodules.py, setup.py
```
(virtualenv_run) [1] ckuehl@dev4-uswest1cdevc:~/pg/yelp-main$ gs
#
#
(virtualenv_run) ckuehl@dev4-uswest1cdevc:~/pg/yelp-main$ gc
Forbid new submodules....................................................Failed
hookid: forbid-new-submodules
blah: new submodule introduced
This commit introduces new submodules.
Did you unintentionally `git add .`?
To fix: git rm {thesubmodule}  # no trailing slash
Also check .gitmodules
```
=> Add forbid-new-submodules to hooks.yaml

.travis.yml, tox.ini
This occurs when there is no global setting for git config options user.name and user.email
An example of the error shown below:
```
E           pre_commit.util.CalledProcessError: Command: ('/usr/bin/git', 'commit', '-m', 'init', '--allow-empty')
E           Return code: 128
E           Expected return code: 0
E           Output: (none)
E           Errors:
E
E               *** Please tell me who you are.
E
E               Run
E
E                 git config --global user.email "you@example.com"
E                 git config --global user.name "Your Name"
E
E               to set your account's default identity.
E               Omit --global to set the identity only in this repository.
E
E               fatal: empty ident name (for <(null)>) not allowed
```
=> Fix test error "fatal: empty ident name (for <(null)>) not allowed"

README.md, pre_commit_hooks/detect_aws_credentials.py, testing/resources/aws_config_with_multiple_sections.ini, testing/resources/aws_config_with_secret.ini, testing/resources/aws_config_with_secret_and_session_token.ini, testing/resources/aws_config_with_session_token.ini, testing/resources/aws_config_without_secrets.ini, testing/resources/with_no_secrets.txt, tests/detect_aws_credentials_test.py
The previous approach for finding AWS credentials was pretty naive and
only covered contents of a single file (`~/.aws/credentials` by default).
The AWS CLI documentation states various other ways to configure
credentials which weren't covered:
https://docs.aws.amazon.com/cli/latest/topic/config-vars.html#credentials
Even that aren't all ways, a look into the code shows:
https://github.com/boto/botocore/blob/develop/botocore/credentials.py
This commit changes the behavior so the hook will behave in a way
that if the AWS CLI is able to obtain credentials from local files,
the hook will find them as well.
The changes in detail are:
- detect AWS session tokens and handle them like secret keys.
- always search credentials in the default AWS CLI file locations
(`~/.aws/config`, …
=> Improve searching for configured AWS credentials

.pre-commit-config.yaml, pre_commit_hooks/trailing_whitespace_fixer.py, tests/trailing_whitespace_fixer_test.py
=> Only return nonzero when rewriting whitespace

pre_commit_hooks/detect_aws_credentials.py, tests/detect_aws_credentials_test.py
In the event that there exists no configuration for AWS credentials and
they are not exported in to the current environment, a flag may be
passed to allow exiting the hook successfully.
Resolves #174
Signed-off-by: Mike Fiedler <miketheman@gmail.com>
=> Add flag to detect-aws-credentials to allow missing keys

README.md
I noticed in our traffic on pre-commit/pre-commit that there were a lot of hits to [this issue](https://github.com/pre-commit/pre-commit/issues/366) presumably due to copy pasting from this readme.
This should reduce frustration in that regard (we'll have to remember to update this whenever bumping the version).
=> Change `sha` in readme to be a real value

pre_commit_hooks/tests_should_end_in_test.py, tests/tests_should_end_in_test_test.py
#181 - Fix to restore regex to handle tests.py, the default Django test format
=> Handling default django test filename of "tests.py"

.gitignore, .pre-commit-hooks.yaml, README.md, hooks.yaml, pre_commit_hooks/sort_simple_yaml.py, setup.py, tests/sort_simple_yaml_test.py
Open source version of closed-source hook written by @chriskuehl 
> Sorts simple YAML files which consist only of top-level keys, preserving comments and blocks.
=> Add sort-simple-yaml hook

pre_commit_hooks/requirements_txt_fixer.py, tests/requirements_txt_fixer_test.py
=> Fix NoneTypeError when requirements file is empty

pre_commit_hooks/requirements_txt_fixer.py, tests/requirements_txt_fixer_test.py
@asottile pointed out that I'd used a list where I could've used a tuple in a different PR. I changed that, then:
1. Made constants PASS=0/FAIL=1 since I found that made the code/tests much more readable
2. Inline the parameterized test params
3. Change an .append() loop to use .extend()
=> Some style tweaks (requirements_txt_fixer)

.pre-commit-hooks.yaml, hooks.yaml
As outlined in https://github.com/pre-commit/pre-commit/pull/551, this hook will become nonfunctional (without this patch) in pre-commit 0.15.0
=> Make check-symlinks 0.15.0 compatible

.pre-commit-hooks.yaml, README.md, hooks.yaml, pre_commit_hooks/mixed_line_ending.py, setup.py, tests/mixed_line_ending_test.py
@nagromc - I squashed your commits, fixed the tests on windows, and applied my review feedback -- I managed to reimplement it in a (imo) much simpler way too!
This supersedes #218 and resolves #196
=> Add mixed-line-ending hook

pre_commit_hooks/trailing_whitespace_fixer.py
`grep` isn't portable so I removed it as well.  This probably makes this hook *slightly* slower as well.
=> Fix trailing-whitespace on macos for non-utf8 files

README.md, pre_commit_hooks/check_builtin_literals.py, testing/resources/builtin_constructors.py, tests/check_builtin_literals_test.py
Fixes an oversight in #249.
The AST differentiates between bare function calls (names) and attribute calls.
=> check-builtin-literals: Ignore function attribute calls

.pre-commit-hooks.yaml
Resolves #268
```console
$ pre-commit try-repo ~/workspace/pre-commit-hooks/ no-commit-to-branch
===============================================================================
Using config:
===============================================================================
repos:
-   repo: /home/asottile/workspace/pre-commit-hooks/
sha: 66eb9d3aec1237b5aae3785b22da6b2f699b5d54
hooks:
-   id: no-commit-to-branch
===============================================================================
[INFO] Initializing environment for /home/asottile/workspace/pre-commit-hooks/.
[INFO] Installing environment for /home/asottile/workspace/pre-commit-hooks/.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
Don't commit to …
```
=> Don't pass filenames for no-commit-to-branch

pre_commit_hooks/trailing_whitespace_fixer.py, tests/trailing_whitespace_fixer_test.py
Resolves #270
Seems some of the tests were testing the wrong behaviour -- oops!
=> Don't add end-of-file newline while trimming whitespace

README.md, pre_commit_hooks/requirements_txt_fixer.py, tests/requirements_txt_fixer_test.py
Should help to deal with that pretty paintuly issue under Ubuntu/Debian
family:
https://bugs.launchpad.net/ubuntu/+source/python-pip/+bug/1635463
=> Provide automatic removal of pkg-resources==0.0.0

.gitignore, pre_commit_hooks/autopep8_wrapper.py, pre_commit_hooks/check_docstring_first.py, pre_commit_hooks/string_fixer.py, testing/util.py, tests/meta_test.py
Makes PR  #276 obsolete.
Extends PR #277
=> Open files as UTF-8

pre_commit_hooks/check_merge_conflict.py, tests/check_merge_conflict_test.py
=> Added --assume-in-merge option for check-merge-conflict

README.md
Current documentation to use the `no-commit-to-branch` is kinda confusing. So updated it to reflect how it correctly works.
=> Fix readme to correctly reflect no-commit-to-branch args

pre_commit_hooks/end_of_file_fixer.py, tests/end_of_file_fixer_test.py
I'm not sure if it's a problem that this approach always replaces a final `\r\n` with `\n`, if that could conflict with the mixed-line-ending hook or Git settings. On one hand, the existing implementation always wrote `\n` if there was no final line break, so this is consistent with that, but then another hook could convert that `\n` to `\r\n`, and this hook would have just ignored it.
=> Fix #326: Handle CRLF in end-of-file-fixer

pre_commit_hooks/mixed_line_ending.py, tests/mixed_line_ending_test.py
Fixes [issue 340](https://github.com/pre-commit/pre-commit-hooks/issues/340).
=> Report failing filenames when --fix=no in mixed-line-endings

.pre-commit-hooks.yaml
flake8 internally implements multiprocessing, disabling pre-commit's improves performance
=> Turn off pre-commit's automated multiprocessing for flake8

.pre-commit-hooks.yaml
=> Don't run check-executables-have-shebangs and trailing-whitespace-fixer hooks for the commit-msg stage

.pre-commit-hooks.yaml
Run check-byte-order-marker against all text types, not just Python files, as discussed in #371 . (Let me know if this PR is too minimal.)
Resolves #371
=> Run check-byte-order-marker against all text types

pre_commit_hooks/check_docstring_first.py, tests/check_docstring_first_test.py
Supersedes #345
CC @x007007007
=> Don't require an encoding for check-docstring-first

README.md, pre_commit_hooks/no_commit_to_branch.py, tests/no_commit_to_branch_test.py
Add wildcard matching to no-commit-to-branch hook, so that commits can be blocked on, for example, all release branches with 'release/*'
Addresses: #375
=> Add regex matching to no-commit-to-branch hook

pre_commit_hooks/check_yaml.py
Resolves #377 
This PR changes a function in `pre_commit_hooks/check_yaml.py` from `open()` to `io.open()`.
=> Changed from open() to io.open()

.pre-commit-hooks.yaml, README.md, pre_commit_hooks/check_toml.py, setup.cfg, tests/check_toml_test.py
This should enable us to validate TOML files, like the controversial `pyproject.toml` ones.
=> Toml checker

pre_commit_hooks/pretty_format_json.py, tests/pretty_format_json_test.py
This PR makes the pretty JSON check more verbose when it encounters errors, that way developers can see which lines are causing errors in order to debug.
I haven't seen any talk about adding this anywhere, but would love to hear the maintainers' thoughts on this.
=> Add logic to print diff between expected and actual JSON

README.md, pre_commit_hooks/trailing_whitespace_fixer.py, tests/trailing_whitespace_fixer_test.py
This PR adds a new flag to the `trailing-whitespace` hook, `--chars`, which allows you to specify a custom set of characters to pass to `rstrip`.
This flag was motivated by Common Lisp, in which a common convention is to use `\f` to delineate sections of code. `trailing-whitespace` considers these by default whitespace, and so strips out the section delimiters users want to preserve. In repositories where this convention is used, a custom value for `--chars` can be specified. This hook is general enough to be used in other use cases if need be, however.
=> trailing-whitespace: add option for custom chars to strip

README.md
=> Document mixed-line-ending limitation for fix={crlf,lf} with git.

README.md
I don't know if this is something that you want to maintain, so feel free to reject the pull request. I just wanted to suggest one of the hooks from here to my team, and wished I could like directly to the correct one like https://github.com/pre-commit/pre-commit-hooks#mixed-line-ending. This pull request allows that.
=> Allow linking directly to each hook

pre_commit_hooks/detect_aws_credentials.py, tests/detect_aws_credentials_test.py
=> Allow arbitrarily encoded files to be checked with detect-aws-credentials

README.md
Fix docs for pretty-format-json: default indent is **2** spaces.
Fixes #456.
=> Fix docs for pretty-format-json: default indent is **2** spaces.

.pre-commit-hooks.yaml, setup.cfg
=> Remove additional remnants of flake8

pre_commit_hooks/check_toml.py, tests/check_toml_test.py
=> Support checking unicode TOML

pre_commit_hooks/check_executables_have_shebangs.py, tests/check_executables_have_shebangs_test.py
=> Check git mode on Windows

pre_commit_hooks/requirements_txt_fixer.py, tests/requirements_txt_fixer_test.py
=> Parse more operators in requirements

pre_commit_hooks/removed.py, tests/removed_test.py
=> hotfix: the user may be define an extra arguments for a removed hook

README.md
Include instructions on how to use files/types/excludes/exclude_types
with the no-commit-to-branch hook, along with the caveat of it allowing
empty commits
=> Document the default always_run behaviour of no-commit-to-branch

pre_commit_hooks/debug_statement_hook.py
This commit adds support for `pydevd_pycharm` debug statements in the `debug-statements`-Hook. I've also sorted the list in alphabetically order as it grows over time (see https://github.com/pre-commit/pre-commit-hooks/commit/43bfa05e8946f394e6967c63cad8875685d4c6b6 for example).
Tested locally on my machine:
```
❯ pre-commit run debug-statements -a
Debug Statements (Python)................................................Failed
- hook id: debug-statements
- exit code: 1
my_python_file.py:221:12 - pydevd_pycharm imported
```
=> debug-statements: Add "pydevd_pycharm" to list of debug statements

pre_commit_hooks/check_executables_have_shebangs.py, tests/check_executables_have_shebangs_test.py
I used the online editor to send the patch. Let me know if you'd like I add a test for it!
We could also consider moving the `zsplit` in the `utils` module.
---
Commit message:
On Windows, all files are "executable". Therefore, to know if a file is supposed to be executed, we check how its attributes were recorded by git: we run a `git ls-files` command in a subprocess.
By default, this command outputs information on multiple lines (file and their data separated by newlines). When a file contains an unusual character, the character is escaped with an integer sequence (such as `\303\261`), and git wraps the whole filename
in double-quotes because of the backslashes. It breaks the current code because we try to open the filename containing the double-quotes: it doesn't exist, of course. …
=> Fix parsing of git output with unusual characters

pre_commit_hooks/file_contents_sorter.py, tests/file_contents_sorter_test.py
Does nothing fancy (no case folding).
But does what I need in my case.
Comments welcome of course.
=> Add a way to do case-insensitive sorting via file-contents-sorter.

README.md, pre_commit_hooks/check_added_large_files.py, tests/check_added_large_files_test.py
The --enforce-all option when provided ensures that all files passed
on the command line are checked against the size limit.  Default
behaviour remains unchanged.
=> Fix #518, provide --enforce-all option to check_added_large_files

.pre-commit-hooks.yaml, README.md, pre_commit_hooks/fix_byte_order_marker.py, setup.cfg, tests/fix_byte_order_marker_test.py
I'm attempting to add automatic fixing of BOMs
=> Attempt to add fixing of BOMs

pre_commit_hooks/file_contents_sorter.py, tests/file_contents_sorter_test.py
Allow file_contents_sorter to unique a file via the new --unique arg.
=> Add --unique arg to file_contents_sorter

README.md, pre_commit_hooks/check_vcs_permalinks.py, tests/check_vcs_permalinks_test.py
I have added an option to inspect the source code of the additional domain, especially useful on GitHub Enterprise.
=> Add --additional-domain to check-vcs-permalinks

.pre-commit-hooks.yaml, README.md, pre_commit_hooks/check_executables_have_shebangs.py, pre_commit_hooks/destroyed_symlinks.py, pre_commit_hooks/util.py, setup.cfg, tests/check_executables_have_shebangs_test.py, tests/destroyed_symlinks_test.py, tests/util_test.py
The hook detects symlinks which are changed to regular files with a content of a path which that symlink was pointing to.
This usually happens on Windows in case when user without a permission for creating symlinks clones repository with symlinks.
~~Some implementation notes: `bytes` is used for filenames in order to avoid having any troubles with encodings. After all, the hook check for destroyed symlinks, not for bad file encoding. `;)`~~
P. S. If you don't think that this hook would be useful for general audience, I'm fine with hosting it in the separate repo. Just wanted to try.
=> New hook 'destroyed-symlinks'

pre_commit_hooks/requirements_txt_fixer.py, tests/requirements_txt_fixer_test.py
=> Fix comments with indents

pre_commit_hooks/check_json.py, testing/resources/duplicate_key_json.json, tests/check_json_test.py
Raise ValueError and return 1 if json contains duplicate keys
Fixes https://github.com/pre-commit/pre-commit-hooks/issues/554
=> Report duplicate keys in check_json

README.md, pre_commit_hooks/no_commit_to_branch.py, tests/no_commit_to_branch_test.py
It's becoming more common to have the primary git branch be called `main` instead of `master` now. With GitHub now making it the [default](https://github.blog/changelog/2020-10-01-the-default-branch-for-newly-created-repositories-is-now-main/) and making it [easier](https://github.com/github/renaming) to transition across, we've started noticing it more in other repositories, and started transferring our repositories over to it.
However, a stage that we missed in several cases was updating the pre-commit hook for `no-commit-to-branch` to block the new name, as we had relied on the default behaviour before.
This patch updates the default behaviour so both `master` and `main` are blocked by default.
~Along with this, I found that all of the tests for this hook failed by default on my …
=> no-commit-to-branch: Add 'main' to branches blocked by default

pre_commit_hooks/pretty_format_json.py
=> Update `pretty-format-json` to write to stdout with utf-8 encoding

.pre-commit-hooks.yaml, README.md, pre_commit_hooks/check_executables_have_shebangs.py, pre_commit_hooks/check_shebang_scripts_are_executable.py, setup.cfg, tests/check_shebang_scripts_are_executable_test.py
First cut, applies on top of #544.
=> Add check for executability of scripts with shebangs

pre_commit_hooks/check_case_conflict.py
fixes #625
performance for this approach on my team's repo:
```
λ py test.py
10001077 function calls in 4.023 seconds
Ordered by: standard name
ncalls  tottime  percall  cumtime  percall filename:lineno(function)
1    0.039    0.039    4.023    4.023 <string>:1(<module>)
4    0.000    0.000    0.000    0.000 _weakrefset.py:38(_remove)
4    0.000    0.000    0.000    0.000 _weakrefset.py:81(add)
3    0.000    0.000    0.289    0.096 check_case_conflict.py:13(lower_set)
3    0.192    0.064    0.289    0.096 check_case_conflict.py:14(<setcomp>)
3189661    1.037    0.000    2.010    0.000 check_case_conflict.py:17(parents)
2    0.000    0.000    2.817    1.409 check_case_conflict.py:25(directories_for)
2    0.807    0.404    2.817    1.409 check_case_conflict.py:26(<setcomp>)
1    0.146 …
```
=> optimize check_case_conflict.parents

.pre-commit-hooks.yaml, pre_commit_hooks/forbid_new_submodules.py, testing/util.py, tests/check_added_large_files_test.py, tests/check_case_conflict_test.py, tests/check_merge_conflict_test.py, tests/destroyed_symlinks_test.py, tests/forbid_new_submodules_test.py, tests/no_commit_to_branch_test.py
=> forbid-new-submodules fixes

pre_commit_hooks/check_executables_have_shebangs.py
Resolves #686 
> Some of the executable error messages suggest using chmod +/-x to toggle the executable bits. This works fine on *nix, but not on windows, and the results range from 'command not found' to doing nothing at all.
> 
> Eg: https://github.com/pre-commit/pre-commit-hooks/blob/56b4a7e506901ff86f8de5c2551bc41f8eacf717/pre_commit_hooks/check_executables_have_shebangs.py#L66
> 
> Instead, this should recommend `git add --chmod=+/-x somepath` when the hook detects it's running on windows.
=> Suggest usable call when executable files lack shebang on Windows

pre_commit_hooks/check_added_large_files.py, tests/check_added_large_files_test.py
`git lfs status` only outputs status for files that are pending some git-lfs related operation.
For usage with --enforce-all, we need the list of all files that are tracked. Ideally, this would
be done using `git lfs ls-files`; however, that doesn't provide a parseable output option
(https://github.com/git-lfs/git-lfs/issues/4679). Therefore, this uses `git check-attr` and uses
the attribute `filter=lfs` to determine which files to consider as git-lfs files.
Fixes: https://github.com/pre-commit/pre-commit-hooks/issues/560
=> Fix check-added-large-files --enforce-all to correctly consider all git-lfs files.

pre_commit_hooks/check_executables_have_shebangs.py
There was already a guard preventing the `check-executables-have-shebangs` hook from raising false positives on win32 by looking up the Git file mode rather than relying on the file mode in the file system. Git already automatically probes the file system for executable bit support. Leverage Git's [`core.fileMode` config variable](https://git-scm.com/docs/git-config#Documentation/git-config.txt-corefileMode) to prevent false positives on all file systems that don't track executable bits.
Fixes #690.
=> Check Git core.fileMode rather than infer from OS.

pre_commit_hooks/check_toml.py, setup.cfg
Closes #755.
Originally this switch was rejected because the hope was that `toml` would be updated at one point, see https://github.com/pre-commit/pre-commit-hooks/pull/608. However, the latest commit is from 1 November 2020 ([commits](https://github.com/uiri/toml/commits/master)) and `tomli` will be part of Python `3.11` so it seems like a good candidate to replace it.
Similar PRs have been used in other "mainstream" projects like https://github.com/python/mypy/pull/12305 and https://github.com/pytest-dev/pytest/pull/9741.
=> Use tomli and tomllib instead of toml

.pre-commit-hooks.yaml
looks like this was accidentally running on `commit-msg` hooks
resolves #777
=> set stages for `check-added-large-files`

.pre-commit-hooks.yaml, README.md, pre_commit_hooks/tests_should_end_in_test.py, tests/tests_should_end_in_test_test.py
additionally I corrected a few tiny things:
- the `.` was not escaped in the regexes
- explicitly named the default mode as `--pytest`
- added a `--unittest` alias to `--django`
=> name-test-tests: add --pytest-test-first convention

README.md
Sort the lines in specified files (defaults to alphabetical). You must provide list of target files as input to it. Note that this hook WILL remove blank lines and does NOT respect any comments.
Sort the lines in specified files (defaults to alphabetical). You must provide the target [`files`](https://pre-commit.com/#config-files) as input, for example:
```yaml
-   id: file-contents-sorter
files: \.gitignore
```
Note that this hook WILL remove blank lines and does NOT respect any comments.
=> Alphabetize & clarify `file-contents-sorter` in README

.pre-commit-hooks.yaml, README.md
Resolves #830 
A naming change for the hook might be welcome but that would probably require every single user to change their configuration…
=> add constraints file to requirements-txt-fixer files

README.md
When `file-contents-sorter` was moved up for alphabetizing, these options were left behind.
=> Fix missing file-contents-sorter options in the README

pre_commit_hooks/debug_statement_hook.py
This patch adds the bpython debugger import `bpdb` to the debug_statements_hook.
Closes #941
=> Add bpdb to debug_statements_hook

pre_commit_hooks/file_contents_sorter.py, tests/file_contents_sorter_test.py
As stated in the documentation: `Note that this hook WILL remove blank lines`. Previously this hook would always add blank a blank line. 
With this fix, if the file is empty, a newline will not be added, and multiple blank lines in a file will be removed.
Fixes #935
=> Fix blank lines in file-contents-sorter plugin

pre_commit_hooks/check_yaml.py
Found a misspelling with `typos`.
=> Fix a typo in check_yaml

README.md
Let's document the behavior and suggest what to do for users of the hook.
Ref: #958, #959
=> Document newline behavior of `file-contents-sorter`

pre_commit_hooks/string_fixer.py, tests/string_fixer_test.py
=> don't rewrite string quotes inside f-strings

.pre-commit-hooks.yaml, README.md, pre_commit_hooks/fix_encoding_pragma.py
=> Add deprecation messaging for `fix-encoding-pragma`

pre_commit_hooks/requirements_txt_fixer.py, tests/requirements_txt_fixer_test.py
This package with an underscore instead of a dash seems to be new behavior (at least on Ubuntu 20.04 with Python 3.8
Fixes #1030
=> Stop pkg_resources from being added as well

.pre-commit-hooks.yaml, README.md, tests/check_illegal_windows_names_test.py
=> Add check for illegal Widnows names

pre_commit_hooks/pretty_format_json.py, tests/pretty_format_json_test.py
=> Continues processing JSONs even if hook fails (fixes #1038)

.pre-commit-hooks.yaml
The 'destroyed-symlinks' hook runs upon 'commit-msg' hook, however when used in 'git submodules', repository scope breaks
> pre_commit_hooks.util.CalledProcessError: (('git', 'status',
> '--porcelain=v2', '-z', '--', '.../COMMIT_EDITMSG'), 0, 128, '',
> b"fatal: .../COMMIT_EDITMSG: '...' is outside repository at '...'\n")
---
---
**Related issues :** Similar to #777 
---
**Test case using `docker run --entrypoint sh --rm -it python:3.12` container for example (+ `4.6.0` workaround) :**
```bash
if ! git config --global --get user.email; then
git config --global user.email 'you@example.com'
git config --global user.name 'Your Name'
fi
mkdir ./main/
cd ./main/
git init
echo '# Main' >./README.md
git add -v ./README.md
git commit -m 'docs(readme): initial commit'
cd ../
mkdir ./submodule1/
cd …
```
=> set stages for `destroyed-symlinks`

.pre-commit-hooks.yaml, tests/check_illegal_windows_names_test.py
Fixes #1048. It took some time to get it right, but I'm pretty sure this covers every possible illegal file name now. 
For reference, the following names are illegal on Windows:
- A name with any of the characters `< > : " \ | ? *` or any characters in the ASCII range `0-31`
- CON, PRN, AUX, NUL, COM0, COM1, COM2, COM3, COM4, COM5, COM6, COM7, COM8, COM9, COM¹, COM², COM³, LPT0, LPT1, LPT2, LPT3, LPT4, LPT5, LPT6, LPT7, LPT8, LPT9, LPT¹, LPT², and LPT³
- A name ending with a space or period
=> Extend check for illegal Windows filenames

pre_commit_hooks/file_contents_sorter.py, tests/file_contents_sorter_test.py
Closes #794: using these flags at the same time results in undefined behavior - the final ordering is not guaranteed as --unique breaks sorting due to passing the contents through a set.
NOTE: I added a newline before and after the mutex group to be consistent with other usages of mutex groups (e.g., check_builtin_literals.py) in this repo.
=> Disallow --unique alongside --ignore-cases in file-contents-sorter

pre_commit_hooks/check_shebang_scripts_are_executable.py
Minor fix to the grammar of the error that prints when check-shebang-scripts fails.
=> Fix grammar of check-shebang-scripts error
